export const FETCH_Locations_REQUEST = 'FETCH_Locations_REQUEST';
export const FETCH_Locations_SUCCESS = 'FETCH_Locations_SUCCESS';
export const FETCH_Locations_FAILURE = 'FETCH_Locations_FAILURE';

export const FETCH_Gender_REQUEST = 'FETCH_Gender_REQUEST';
export const FETCH_Gender_SUCCESS = 'FETCH_Gender_SUCCESS';
export const FETCH_Gender_FAILURE = 'FETCH_Gender_FAILURE';


export const FETCH_ArabicEducation_REQUEST = 'FETCH_ArabicEducation_REQUEST';
export const FETCH_ArabicEducation_SUCCESS = 'FETCH_ArabicEducation_SUCCESS';
export const FETCH_ArabicEducation_FAILURE = 'FETCH_ArabicEducation_FAILURE'; 

export const FETCH_QURANLEVEL_REQUEST = 'FETCH_QURANLEVEL_REQUEST';
export const FETCH_QURANLEVEL_SUCCESS = 'FETCH_QURANLEVEL_SUCCESS';
export const FETCH_QURANLEVEL_FAILURE = 'FETCH_QURANLEVEL_FAILURE';


export const FETCH_LANGUAGES_REQUEST = 'FETCH_LANGUAGES_REQUEST';
export const FETCH_LANGUAGES_SUCCESS = 'FETCH_LANGUAGES_SUCCESS';
export const FETCH_LANGUAGES_FAILURE = 'FETCH_LANGUAGES_FAILURE'; 


export const FETCH_AGZAACOUNT_REQUEST = 'FETCH_AGZAACOUNT_REQUEST';
export const FETCH_AGZAACOUNT_SUCCESS = 'FETCH_AGZAACOUNT_SUCCESS';
export const FETCH_AGZAACOUNT_FAILURE = 'FETCH_AGZAACOUNT_FAILURE';

export const FETCH_GOALS_REQUEST = 'FETCH_GOALS_REQUEST';
export const FETCH_GOALS_SUCCESS = 'FETCH_GOALS_SUCCESS';
export const FETCH_GOALS_FAILURE = 'FETCH_GOALS_FAILURE';