export const VERIFY_PHONE_START = 'VERIFY_PHONE_START'
export const VERIFY_PHONE_SUCCESS = 'VERIFY_PHONE_SUCCESS'
export const VERIFY_PHONE_FAIL = 'VERIFY_PHONE_FAIL'

export const CHECK_AUTH = 'CHECK_AUTH'
